### ISSUE TITLE
Nuxt and Framework Cannot npm run generate (site)

### ISSUE THREAD

**Issue by jancel** [Qonfucius/nuxt-fontawesome#2]
I've reproduced here: https://github.com/jancel/fontawesome-quonfucious-bug

Steps to reproduce:
1. vue init nuxt-community/starter-template issue-reproduction
1. cd issue-reproduction
1. yarn install
1. yarn add qonfucius-nuxt-fontawesome
1. yarn add @ fortawesome/fontawesome-free-brands  # remove space between @
1. yarn add @ fortawesome/fontawesome-free-solid # remove space between @
1. Add modules to nuxt.config.js
```javascript  
modules: [
    ['qonfucius-nuxt-fontawesome', { componentName: 'fa-icon', packs: [{
      package: '@fortawesome/fontawesome-free-brands',
        icons: ['faGithub', 'faFontAwesome', 'faLinkedin', 'faTwitter', 'faGooglePlus', 'faGithubAlt', 'faSkype'],
      },
      {
        package: '@fortawesome/fontawesome-free-solid',
        icons: ['faDownload','faPaperPlane']
      }] 
    }],
  ],
```
1. Simply run yarn run generate to reproduce the error below
```zsh
yarn run v1.3.2
$ nuxt generate
  nuxt:generate Generating... +0ms
  nuxt:build App root: /Users/jancel/develop/fontawesome5-qonfucious +0ms
  nuxt:build Generating /Users/jancel/develop/fontawesome5-qonfucious/.nuxt files... +1ms
  nuxt:build Generating files... +49ms
  nuxt:build Generating routes... +5ms
  nuxt:build Building files... +20ms
Build completed in 4.587s

Hash: db8ba3fcbcfd64fe3120
Version: webpack 3.8.1
Time: 4591ms
                                  Asset     Size  Chunks                    Chunk Names
    pages/index.0bc01168561d88a23cea.js  3.95 kB       0  [emitted]         pages/index
layouts/default.1a16b0a54b8ae41aea35.js   1.4 kB       1  [emitted]         layouts/default
         common.08e16f276bcd6467c774.js  1.14 MB       2  [emitted]  [big]  common
            app.2608f2604e65f7c25854.js  25.7 kB       3  [emitted]         app
       manifest.db8ba3fcbcfd64fe3120.js  1.59 kB       4  [emitted]         manifest
 + 8 hidden assets

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
This can impact web performance.
Assets:
  common.08e16f276bcd6467c774.js (1.14 MB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (1 MB). This can impact web performance.
Entrypoints:
  app (1.17 MB)
      manifest.db8ba3fcbcfd64fe3120.js
      common.08e16f276bcd6467c774.js
      app.2608f2604e65f7c25854.js
  common (1.14 MB)
      manifest.db8ba3fcbcfd64fe3120.js
      common.08e16f276bcd6467c774.js


ERROR in common.08e16f276bcd6467c774.js from UglifyJs
Unexpected token: name (isLastCharLower) [./node_modules/@fortawesome/vue-fontawesome/index.js:12,0][common.08e16f276bcd6467c774.js:16108,5]
Error: Webpack build exited with errors
    at /Users/jancel/develop/fontawesome5-qonfucious/node_modules/nuxt/lib/builder/builder.js:498:27
    at emitRecords.err (/Users/jancel/develop/fontawesome5-qonfucious/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/jancel/develop/fontawesome5-qonfucious/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/jancel/develop/fontawesome5-qonfucious/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/jancel/develop/fontawesome5-qonfucious/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/jancel/develop/fontawesome5-qonfucious/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/jancel/develop/fontawesome5-qonfucious/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/jancel/develop/fontawesome5-qonfucious/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/jancel/develop/fontawesome5-qonfucious/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/jancel/develop/fontawesome5-qonfucious/node_modules/webpack/lib/Compiler.js:354:15)
    at /Users/jancel/develop/fontawesome5-qonfucious/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/jancel/develop/fontawesome5-qonfucious/node_modules/async/dist/async.js:1050:13)
    at /Users/jancel/develop/fontawesome5-qonfucious/node_modules/async/dist/async.js:958:16
    at /Users/jancel/develop/fontawesome5-qonfucious/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by pand-app** [comment]
Hello,

For now, you can fix it by disabling uglifyJS : 
```javascript
{
  build: {
    extend (config) {
      config.plugins = config.plugins.filter((plugin) => plugin.constructor.name !== 'UglifyJsPlugin')
    }
  },
}
```

**Comment by pand-app** [comment]
Hello,

Example provided in source is working, I close issue, feel free to reopen.
